name: solver-cicd

on:
  push:
    branch: ["*"]

jobs:
  test_solve:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: make install-dependencies
    - name: Test with pytest
      run: make test
    - name: Solve - Python
      run: make solve
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.20.0'
    - name: Solve - Go
      run: make solve-go
